### PR TITLE
Adjust page width and center content

### PR DESCRIPTION
**Pull request by AlessandroDani**

### CODE REVIEW

**Comment by byandrev** [comment]
Upload images of the changes. 🥸

**Comment by AlessandroDani** [comment]
When I was checking the page, I noticed that the content was displayed without witdh space. So I made some modifications. Please check it out and let me know your opinion :D

**Comment by AlessandroDani** [comment]
I'm sorry, Would you be more specific about Images?

**Comment by byandrev** [comment]
What changes did you make? I need to see it

**Comment by AlessandroDani** [comment]
I add space between both sides of the page and center titles

**Pull request merged**
